[tool.poetry]
name = "csse6400-week1-practical"
version = "0.1.0"
description = ""
authors = ["Brook Queree <github.com/bhq12>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
